server:
  port: 8081

spring:
  application:
    name: addressbook

  datasource:
    url: jdbc:mysql://localhost:3307/addressdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    addresses: localhost:5672

  data:
    redis:
      host: localhost
      port: 6379