spring:
  application:
    name: addressbook

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:addressbookdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  logging:
    file:
      name: logs/application.log


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: apurvkumar1103@gmail.com
    password: wcdu yfdh yogt mwnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    addresses: localhost:5672

  data:
    redis:
      host: localhost
      port: 6379
